<?php

namespace WardLeonard\DiscoBundle\Repository;

/**
 * DiskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DiskRepository extends \Doctrine\ORM\EntityRepository
{
}
