<?php

namespace WardLeonard\DiscoBundle\Repository;

/**
 * LyricRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LyricRepository extends \Doctrine\ORM\EntityRepository
{
}
